version: "3.3"
services:
  db:
    image: mariadb:10.8.2
    container_name: magnus-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /data/magnus/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=magnus
      - MYSQL_USER=magnus
      - MYSQL_PASSWORD=magnus.cc
      - MYSQL_ROOT_PASSWORD=magnus.cc
  magnus:
    image: magnus:1.0.0
    container_name: magnus
    privileged: true
    restart: always
    volumes:
      - /data/magnus/service:/data/magnus
      - /data/magnus/repos:/data/repos
    ports:
      - "80:80"
    environment:
      - SPUG_DOCKER_VERSION=v3.2.4
      - MYSQL_DATABASE=magnus
      - MYSQL_USER=magnus
      - MYSQL_PASSWORD=magnus.cc
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
